### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by stovberpv** [Ramotion/expanding-collection-android#6]
**MainActivity call** 
`FragmentManager fragmentManager = getSupportFragmentManager();
FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
fragmentTransaction.replace(R.id.frame_container, fragmentCatalog);
fragmentTransaction.addToBackStack(globals.getKeyBackStack());
fragmentTransaction.commit();`

**In FragmentCatalog**
_on_ 
`@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)`
_at line_
`ecPagerView.setBackgroundSwitcherView((ECBackgroundSwitcherView) view.findViewById(R.id.ec_bg_switcher_element));`
_raise_
`java.lang.NullPointerException: key == null || value == null
                                                                       at android.util.LruCache.put(LruCache.java:166)
                                                                       at com.ramotion.expandingcollection.BackgroundBitmapCache.addBitmapToBgMemoryCache(BackgroundBitmapCache.java:43)
                                                                       at com.ramotion.expandingcollection.ECBackgroundSwitcherView.updateCurrentBackground(ECBackgroundSwitcherView.java:134)
                                                                       at com.ramotion.expandingcollection.ECPagerView.setBackgroundSwitcherView(ECPagerView.java:190)
                                                                       at com.app.fragment.FragmentCatalog.onCreateView(FragmentCatalog.java:117)
                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)`

**Comment by stovberpv** [comment]
bm = decodeResourceStream(res, value, is, null, opts); return null
****
![image](https://user-images.githubusercontent.com/13037514/27013132-b6d2c9b6-4ee6-11e7-9040-8c0d58065373.png)
****
![image](https://user-images.githubusercontent.com/13037514/27013138-d97285c4-4ee6-11e7-800f-b7c4264dbae9.png)

**Comment by stovberpv** [comment]
Fixed. My mistake. jpg was corrupted.
